- name: Set hostname
  hostname:
    name: "delta"


# apt packages
- name: Update and upgrade packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    autoremove: yes
    upgrade: yes

- name: Install packages (Debian and Ubuntu)
  apt:
    name: "{{ packages }}"
    state: latest


# group setup
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'


# user
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ username }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash
    update_password: on_create

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ copy_local_key }}"

# ssh server config
- name: Disable SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  register: sshd_config

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
  register: sshd_config

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed


# firewall
- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming
